version: "3.9"

services:
  backend:
    build: .
    container_name: devsters-backend
    working_dir: /app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
      - ./frontend/dist:/app/frontend
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true

  frontend:
    image: node:20-slim
    container_name: devsters-frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: sh -c "npm ci && npm run build -- --watch"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
